var bodies = [
  {
    "name": "Francisco Bolognesi",
    "popularity": 10,
    "life": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Miguel Grau",
    "popularity": 10,
    "life": 7,
    "delay_item": 7,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "AntiCovid (SET)",
    "popularity": 10,
    "life": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Sweet Set",
    "popularity": 10,
    "defense": 10,
    "dig": 10,
    "attack": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "KoreaGunba Silver",
    "popularity": 15,
    "delay": 10,
    "defense": 22,
    "life": 22,
    "shield": 25,
    "attack": 0,
    "dig": 0,
    "delay_item": 0
  },
  {
    "name": "Naruto Uzumaki",
    "popularity": 15,
    "attack": 10,
    "defense": 20,
    "life": 12,
    "shield": 12,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Kakashi Hatake",
    "popularity": 15,
    "life": 20,
    "delay_item": 12,
    "shield": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0
  },
  {
    "name": "Kiba",
    "popularity": 10,
    "attack": 12,
    "life": 10,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Monkey D. Luffy",
    "popularity": 15,
    "delay": 12,
    "attack": 10,
    "defense": 15,
    "dig": 12,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Popeye",
    "popularity": 10,
    "attack": 20,
    "delay_item": 10,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Mario Gold",
    "popularity": 15,
    "delay": 10,
    "defense": 10,
    "life": 15,
    "delay_item": 10,
    "shield": 15,
    "attack": 0,
    "dig": 0
  },
  {
    "name": "Mermaid",
    "popularity": 10,
    "delay": 5,
    "life": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Transformer",
    "popularity": 15,
    "delay": 10,
    "defense": 15,
    "life": 10,
    "shield": 15,
    "attack": 0,
    "dig": 0,
    "delay_item": 0
  },
  {
    "name": "Gold Mask",
    "popularity": 15,
    "delay": 10,
    "attack": 30,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Punkie",
    "popularity": 10,
    "attack": 5,
    "defense": 9,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Groom",
    "popularity": 10,
    "attack": 5,
    "life": 10,
    "shield": 10,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Flight Attendant",
    "popularity": 10,
    "delay": 7,
    "attack": 7,
    "defense": 5,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Hanbok",
    "popularity": 10,
    "attack": 5,
    "defense": 10,
    "delay_item": 10,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Harry Potter",
    "popularity": 10,
    "attack": 10,
    "defense": 10,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Pop Star",
    "popularity": 12,
    "attack": 7,
    "defense": 7,
    "life": 15,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Iced Hero",
    "popularity": 10,
    "attack": 10,
    "defense": 15,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "LadyBird",
    "popularity": 10,
    "delay": 10,
    "attack": 5,
    "life": 5,
    "delay_item": 5,
    "defense": 0,
    "dig": 0,
    "shield": 0
  },
  {
    "name": "Zeus",
    "popularity": 20,
    "delay": 15,
    "attack": 10,
    "life": 10,
    "delay_item": 10,
    "dig": 25,
    "defense": 0,
    "shield": 0
  },
  {
    "name": "Hephaestus",
    "popularity": 20,
    "delay": 15,
    "attack": 20,
    "dig": 25,
    "defense": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Hades",
    "popularity": 20,
    "attack": 15,
    "defense": 20,
    "life": 15,
    "delay_item": 15,
    "dig": 15,
    "shield": 20,
    "delay": 0
  },
  {
    "name": "Aphrodite",
    "popularity": 20,
    "delay": 13,
    "defense": 25,
    "life": 18,
    "dig": 10,
    "attack": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Bright Light",
    "popularity": 15,
    "defense": 7,
    "delay_item": 7,
    "shield": 10,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0
  },
  {
    "name": "Pikachu Costume",
    "popularity": 20,
    "delay": 23,
    "attack": 15,
    "delay_item": 23,
    "dig": 10,
    "defense": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Glotzy",
    "popularity": 12,
    "delay": 5,
    "life": 12,
    "shield": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay_item": 0
  },
  {
    "name": "Observador X",
    "popularity": 12,
    "defense": 12,
    "life": 12,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Zetsu",
    "delay": 10,
    "life": 10,
    "delay_item": 5,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Yahiko",
    "popularity": 15,
    "delay": 5,
    "life": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Naruto Sabio",
    "popularity": 10,
    "life": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Itachi Uchiha",
    "popularity": 10,
    "attack": 7,
    "defense": 5,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Glotzy",
    "popularity": 12,
    "attack": 8,
    "life": 10,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Mr Gum",
    "popularity": 10,
    "delay": 15,
    "attack": 10,
    "life": 5,
    "dig": 8,
    "defense": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Heavenly Knight",
    "popularity": 10,
    "delay": 15,
    "defense": 7,
    "life": 10,
    "attack": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Glowing Warrior",
    "popularity": 10,
    "attack": 10,
    "defense": 5,
    "delay_item": 10,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Raccoon",
    "popularity": 10,
    "attack": 5,
    "life": 7,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Pony",
    "popularity": 10,
    "delay": 20,
    "attack": 10,
    "life": 5,
    "defense": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Popcorn SET",
    "popularity": 15,
    "delay": 12,
    "attack": 12,
    "defense": 15,
    "dig": 12,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Dragon Costume",
    "popularity": 15,
    "delay": 15,
    "defense": 20,
    "delay_item": 20,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Jr. Wizard",
    "popularity": 5,
    "delay": 20,
    "attack": 25,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "KoreaGunba",
    "delay": 12,
    "defense": 25,
    "life": 18,
    "shield": 18,
    "attack": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Boy's fur coat",
    "defense": 6,
    "life": 13,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Toadstool",
    "popularity": 3,
    "delay": 5,
    "defense": 5,
    "delay_item": 5,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Dragon Set",
    "popularity": 10,
    "delay": 14,
    "defense": 12,
    "life": 20,
    "dig": 5,
    "attack": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Elf",
    "popularity": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Dark Man",
    "popularity": 10,
    "delay": 7,
    "life": 9,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Doe",
    "popularity": 10,
    "delay": 10,
    "attack": 3,
    "life": 5,
    "delay_item": 5,
    "defense": 0,
    "dig": 0,
    "shield": 0
  },
  {
    "name": "Water",
    "popularity": 15,
    "delay": 5,
    "defense": 5,
    "life": 20,
    "shield": 25,
    "attack": 0,
    "dig": 0,
    "delay_item": 0
  },
  {
    "name": "Gantz",
    "popularity": 12,
    "delay": 12,
    "shield": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "BFX",
    "popularity": 12,
    "attack": 10,
    "life": 5,
    "dig": 7,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Sacred Angel",
    "popularity": 15,
    "delay": 15,
    "attack": 15,
    "defense": 15,
    "life": 5,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Fruit",
    "popularity": 10,
    "delay": 7,
    "defense": 5,
    "life": 5,
    "attack": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Alyan",
    "popularity": 10,
    "attack": 5,
    "defense": 5,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Arabian Prince",
    "attack": 10,
    "dig": 10,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Ent Warrior",
    "popularity": 5,
    "delay": 3,
    "attack": 14,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Mr. Sushi",
    "defense": 10,
    "life": 10,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Red Devil",
    "popularity": 6,
    "attack": 3,
    "life": 6,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Orange Blade",
    "popularity": 6,
    "delay": 6,
    "delay_item": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Disco Suit",
    "popularity": 6,
    "delay": 9,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Perú",
    "popularity": 15,
    "defense": 7,
    "life": 5,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Heavenly",
    "popularity": 15,
    "attack": 15,
    "defense": 14,
    "life": 15,
    "delay_item": 15,
    "dig": 15,
    "shield": 13,
    "delay": 0
  },
  {
    "name": "Air Robot",
    "popularity": 12,
    "attack": 7,
    "defense": 16,
    "delay_item": 4,
    "shield": 9,
    "dig": 0,
    "life": 0,
    "delay": 0
  },
  {
    "name": "Happy Day",
    "popularity": 10,
    "defense": 5,
    "life": 5,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Golden man",
    "popularity": 10,
    "delay": 10,
    "life": 5,
    "shield": 5,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay_item": 0
  },
  {
    "name": "Mummy (RARE)",
    "popularity": 25,
    "delay": 10,
    "life": 25,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Acolyte",
    "popularity": 12,
    "delay": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Green Alien",
    "popularity": 15,
    "attack": 10,
    "defense": 5,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Blond",
    "popularity": 15,
    "life": 10,
    "shield": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Agez",
    "popularity": 15,
    "attack": 10,
    "defense": 10,
    "life": 10,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Jiren",
    "popularity": 21,
    "delay": 21,
    "attack": 19,
    "delay_item": 21,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Ultra Instinct",
    "popularity": 21,
    "delay": 23,
    "attack": 10,
    "delay_item": 23,
    "dig": 10,
    "defense": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "White",
    "popularity": 20,
    "delay": 15,
    "life": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Happy Easter",
    "popularity": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Rabbit",
    "popularity": 10,
    "attack": 5,
    "life": 5,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Black Dress",
    "popularity": 9,
    "life": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Flamingo",
    "popularity": 18,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Military Suit",
    "popularity": 6,
    "defense": 6,
    "shield": 3,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Road Shooter",
    "popularity": 3,
    "delay": 6,
    "attack": 6,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Black Cloak",
    "popularity": 6,
    "attack": 6,
    "defense": 6,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Street Fighter",
    "delay": 6,
    "delay_item": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Indian Fighter",
    "delay": 6,
    "life": 6,
    "delay_item": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Hip-Hop Wear",
    "popularity": 9,
    "delay": 3,
    "delay_item": 4,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Mummy Clothing",
    "popularity": 3,
    "attack": 6,
    "life": 9,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Wood Body",
    "popularity": 3,
    "life": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Baseball Jacket",
    "delay": 3,
    "delay_item": 6,
    "shield": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "popularity": 0
  },
  {
    "name": "Raincoat",
    "defense": 6,
    "delay_item": 3,
    "shield": 3,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0
  },
  {
    "name": "Duke Suit",
    "popularity": 6,
    "attack": 6,
    "defense": 6,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Indian Wear 2",
    "delay": 3,
    "attack": 6,
    "delay_item": 6,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "High School Band",
    "defense": 3,
    "shield": 3,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Ballroom Suit",
    "popularity": 3,
    "delay_item": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "SWAT Combat",
    "attack": 3,
    "defense": 9,
    "life": 6,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Officer Uniform",
    "popularity": 6,
    "attack": 6,
    "life": 6,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Napoleon",
    "defense": 25,
    "life": 10,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Legendary Samurai",
    "popularity": 20,
    "attack": 20,
    "defense": 20,
    "life": 20,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Prince Of Fire",
    "popularity": 18,
    "delay": 18,
    "attack": 18,
    "dig": 18,
    "defense": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Marvin T.M",
    "popularity": 15,
    "life": 40,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Space Robot",
    "popularity": 15,
    "delay": 5,
    "defense": 25,
    "delay_item": 5,
    "dig": 5,
    "shield": 25,
    "attack": 0,
    "life": 0
  },
  {
    "name": "White Wolf",
    "popularity": 15,
    "delay": 10,
    "defense": 10,
    "delay_item": 5,
    "dig": 10,
    "attack": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Kind Skeleton",
    "popularity": 15,
    "attack": 10,
    "defense": 5,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Rat Boy",
    "popularity": 20,
    "attack": 20,
    "life": 15,
    "dig": 25,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Aztec Warrior",
    "popularity": 15,
    "delay": 15,
    "defense": 5,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Fire Boy",
    "popularity": 15,
    "delay": 5,
    "attack": 10,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Warrior Of Light",
    "popularity": 15,
    "delay": 10,
    "life": 5,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Man Of Crystals",
    "popularity": 10,
    "delay": 15,
    "attack": 12,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Fire Man",
    "popularity": 10,
    "delay": 10,
    "defense": 5,
    "delay_item": 5,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Chick Magnet",
    "popularity": 15,
    "delay": 5,
    "attack": 20,
    "life": 15,
    "delay_item": 20,
    "shield": 20,
    "defense": 0,
    "dig": 0
  },
  {
    "name": "Flower Buddies",
    "delay": 18,
    "defense": 15,
    "delay_item": 15,
    "dig": 15,
    "attack": 0,
    "life": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Fabre Clothing",
    "life": 9,
    "delay_item": 6,
    "shield": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0
  },
  {
    "name": "Mechanic Armour",
    "defense": 9,
    "life": 9,
    "delay_item": 3,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Devil Clothing",
    "delay": 6,
    "attack": 6,
    "life": 6,
    "defense": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Hawaiian Wear",
    "popularity": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Dark Angel",
    "attack": 15,
    "defense": 15,
    "life": 25,
    "shield": 8,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Gladiator",
    "delay": 3,
    "attack": 6,
    "defense": 6,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Indian Wear",
    "delay": 3,
    "life": 6,
    "delay_item": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Thanksgiving",
    "popularity": 9,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Ranger Wear",
    "delay_item": 6,
    "dig": 6,
    "shield": 3,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0
  },
  {
    "name": "Warrior A",
    "attack": 6,
    "defense": 3,
    "life": 3,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Chinese Dress",
    "popularity": 6,
    "delay_item": 3,
    "shield": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0
  },
  {
    "name": "Great King",
    "attack": 3,
    "defense": 6,
    "life": 3,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Korean Dress",
    "popularity": 9,
    "life": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Arabian Dress",
    "popularity": 6,
    "life": 3,
    "delay_item": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Safari Wear",
    "popularity": 6,
    "life": 3,
    "dig": 3,
    "attack": 0,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Swim Suit A",
    "popularity": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Pharaoh",
    "attack": 6,
    "defense": 6,
    "life": 9,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Navy Uniform",
    "popularity": 6,
    "life": 3,
    "dig": 6,
    "attack": 0,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Rider Uniform",
    "popularity": 3,
    "delay_item": 9,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Urban",
    "popularity": 10,
    "delay": 5,
    "defense": 5,
    "life": 5,
    "attack": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Red Devil II",
    "popularity": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Space Suit A",
    "popularity": 3,
    "defense": 12,
    "life": 3,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Heavy Armour",
    "defense": 12,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Light Armour",
    "popularity": 3,
    "defense": 6,
    "delay_item": 3,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Roman General",
    "delay": 3,
    "attack": 6,
    "delay_item": 6,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Pirate Captain",
    "popularity": 3,
    "attack": 12,
    "delay_item": 3,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Shoulder Strap",
    "popularity": 3,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "School Uniform",
    "popularity": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Sanji",
    "popularity": 15,
    "delay": 10,
    "defense": 5,
    "dig": 5,
    "attack": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Man Ears",
    "popularity": 10,
    "delay": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Snorlax",
    "popularity": 15,
    "dig": 15,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Flash",
    "popularity": 15,
    "defense": 5,
    "delay_item": 5,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Urban Boy",
    "popularity": 15,
    "attack": 7,
    "life": 7,
    "dig": 5,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "SSJ Legendario",
    "delay": 15,
    "defense": 10,
    "delay_item": 20,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "WarRed Evil",
    "popularity": 10,
    "defense": 5,
    "delay_item": 5,
    "shield": 5,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0
  },
  {
    "name": "Timmy Turner",
    "popularity": 10,
    "defense": 5,
    "delay_item": 5,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Condorito",
    "popularity": 15,
    "delay": 5,
    "delay_item": 5,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Shadow",
    "popularity": 15,
    "defense": 7,
    "delay_item": 5,
    "dig": 9,
    "attack": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Wiss",
    "popularity": 15,
    "defense": 7,
    "delay_item": 6,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Jiraiya",
    "popularity": 10,
    "attack": 5,
    "life": 9,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Madara Uchiha",
    "popularity": 10,
    "attack": 9,
    "life": 5,
    "dig": 5,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Nyx Jomel",
    "popularity": 12,
    "delay": 5,
    "attack": 10,
    "dig": 20,
    "defense": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Orochimaru",
    "popularity": 10,
    "attack": 10,
    "delay_item": 15,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Blue",
    "popularity": 10,
    "defense": 9,
    "life": 5,
    "delay_item": 10,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Magic",
    "popularity": 10,
    "attack": 10,
    "life": 7,
    "dig": 5,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Locked",
    "delay": 15,
    "attack": 10,
    "life": 5,
    "delay_item": 7,
    "shield": 5,
    "defense": 0,
    "dig": 0,
    "popularity": 0
  },
  {
    "name": "Mario Bros",
    "popularity": 10,
    "attack": 10,
    "delay_item": 5,
    "shield": 5,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0
  },
  {
    "name": "Boruto Uzumaki",
    "popularity": 10,
    "attack": 5,
    "dig": 7,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Naruto Rikudou",
    "popularity": 10,
    "defense": 5,
    "dig": 7,
    "attack": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Kid Buu",
    "popularity": 10,
    "defense": 5,
    "delay_item": 9,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Donald",
    "popularity": 10,
    "attack": 10,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Roronoa Zoro",
    "popularity": 15,
    "defense": 5,
    "shield": 7,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Maestro Rochi",
    "popularity": 10,
    "defense": 9,
    "dig": 6,
    "attack": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Mario Mars",
    "popularity": 10,
    "attack": 5,
    "life": 5,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Gorillaz",
    "popularity": 10,
    "attack": 9,
    "delay_item": 10,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Crash",
    "popularity": 10,
    "delay": 5,
    "defense": 10,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Kirito",
    "popularity": 10,
    "attack": 10,
    "delay_item": 5,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Cell",
    "attack": 10,
    "life": 5,
    "delay_item": 10,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Andres",
    "popularity": 10,
    "defense": 15,
    "life": 10,
    "delay_item": 5,
    "shield": 15,
    "attack": 0,
    "dig": 0,
    "delay": 0
  },
  {
    "name": "Anonymous",
    "popularity": 10,
    "attack": 10,
    "life": 5,
    "shield": 15,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Shadow Warrior",
    "popularity": 10,
    "delay": 10,
    "defense": 10,
    "delay_item": 10,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Zeno Sama",
    "defense": 20,
    "life": 20,
    "dig": 5,
    "shield": 20,
    "attack": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Nyx Blade",
    "delay": 10,
    "defense": 9,
    "life": 5,
    "delay_item": 5,
    "attack": 0,
    "dig": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Euryalus",
    "popularity": 10,
    "defense": 5,
    "life": 5,
    "shield": 5,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Enchanted",
    "attack": 5,
    "defense": 10,
    "delay_item": 5,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Bomberman",
    "popularity": 10,
    "attack": 5,
    "life": 5,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Tony Chopper",
    "popularity": 10,
    "defense": 19,
    "dig": 5,
    "attack": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Boxeador",
    "attack": 15,
    "life": 10,
    "dig": 9,
    "defense": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Warrior of lights",
    "popularity": 10,
    "delay": 10,
    "attack": 10,
    "delay_item": 10,
    "dig": 10,
    "shield": 15,
    "defense": 0,
    "life": 0
  },
  {
    "name": "Yoda",
    "popularity": 10,
    "delay": 10,
    "shield": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "Luke Skywalker",
    "popularity": 6,
    "life": 6,
    "delay_item": 6,
    "shield": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0
  },
  {
    "name": "Brock",
    "popularity": 10,
    "defense": 20,
    "life": 10,
    "dig": 5,
    "shield": 10,
    "attack": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Gohan Dbz Super",
    "popularity": 5,
    "attack": 10,
    "defense": 10,
    "life": 5,
    "dig": 10,
    "shield": 10,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Zamasu",
    "popularity": 10,
    "delay": 13,
    "attack": 10,
    "defense": 15,
    "life": 5,
    "delay_item": 5,
    "dig": 10,
    "shield": 10
  },
  {
    "name": "Pokegamer",
    "popularity": 15,
    "attack": 14,
    "defense": 10,
    "life": 14,
    "delay_item": 5,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Christmas",
    "popularity": 10,
    "attack": 25,
    "life": 10,
    "shield": 15,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Saul",
    "popularity": 10,
    "attack": 15,
    "life": 15,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Creature",
    "attack": 15,
    "defense": 10,
    "dig": 5,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "One Punch Man",
    "popularity": 10,
    "delay": 10,
    "attack": 15,
    "defense": 15,
    "dig": 10,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Jack Skellington",
    "popularity": 10,
    "life": 20,
    "shield": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Jocker",
    "popularity": 12,
    "delay": 9,
    "attack": 5,
    "defense": 7,
    "delay_item": 10,
    "shield": 3,
    "dig": 0,
    "life": 0
  },
  {
    "name": "Flame Man",
    "popularity": 20,
    "delay": 23,
    "attack": 14,
    "delay_item": 17,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Power Ranger",
    "delay": 10,
    "life": 15,
    "shield": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Polar Bear",
    "popularity": 25,
    "attack": 10,
    "defense": 10,
    "life": 10,
    "delay_item": 10,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Unicorn",
    "popularity": 15,
    "delay": 10,
    "defense": 5,
    "shield": 10,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "Lion Boy",
    "delay": 10,
    "life": 20,
    "shield": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Robotic",
    "popularity": 17,
    "delay": 10,
    "attack": 15,
    "life": 10,
    "delay_item": 15,
    "shield": 5,
    "defense": 0,
    "dig": 0
  },
  {
    "name": "Whisper Thunderbolt",
    "popularity": 10,
    "life": 10,
    "delay_item": 5,
    "shield": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0
  },
  {
    "name": "Nyx Silver",
    "popularity": 10,
    "defense": 15,
    "delay_item": 10,
    "dig": 20,
    "shield": 10,
    "attack": 0,
    "life": 0,
    "delay": 0
  },
  {
    "name": "Dragon Man",
    "popularity": 20,
    "delay": 10,
    "defense": 10,
    "life": 20,
    "shield": 15,
    "attack": 0,
    "dig": 0,
    "delay_item": 0
  },
  {
    "name": "Viking King",
    "popularity": 15,
    "defense": 14,
    "life": 10,
    "dig": 15,
    "shield": 10,
    "attack": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Zaimoon",
    "popularity": 15,
    "delay": 10,
    "delay_item": 16,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Athanos",
    "popularity": 15,
    "attack": 10,
    "defense": 5,
    "life": 10,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Painter Body",
    "popularity": 25,
    "attack": 25,
    "life": 25,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Spencer",
    "popularity": 15,
    "delay": 10,
    "delay_item": 5,
    "dig": 10,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Belkin",
    "popularity": 15,
    "delay": 7,
    "defense": 15,
    "life": 10,
    "attack": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Birdman",
    "popularity": 20,
    "delay": 15,
    "defense": 10,
    "shield": 15,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "Super Hero",
    "attack": 11,
    "life": 15,
    "delay_item": 13,
    "dig": 10,
    "defense": 0,
    "delay": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Olish Body",
    "popularity": 11,
    "delay": 7,
    "defense": 20,
    "dig": 15,
    "shield": 11,
    "attack": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "Blue Man",
    "delay": 5,
    "defense": 7,
    "delay_item": 10,
    "shield": 5,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "popularity": 0
  },
  {
    "name": "Neo Observador",
    "popularity": 20,
    "delay": 15,
    "attack": 5,
    "life": 5,
    "delay_item": 16,
    "dig": 25,
    "defense": 0,
    "shield": 0
  },
  {
    "name": "King Kong",
    "popularity": 10,
    "delay": 5,
    "life": 15,
    "delay_item": 5,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "shield": 0
  },
  {
    "name": "Matrix",
    "delay": 10,
    "attack": 8,
    "defense": 8,
    "delay_item": 25,
    "shield": 20,
    "dig": 0,
    "life": 0,
    "popularity": 0
  },
  {
    "name": "Nak",
    "popularity": 18,
    "delay": 15,
    "attack": 5,
    "delay_item": 15,
    "dig": 25,
    "defense": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Armor",
    "popularity": 18,
    "delay": 5,
    "attack": 25,
    "life": 10,
    "dig": 15,
    "defense": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Red",
    "popularity": 18,
    "attack": 18,
    "defense": 18,
    "life": 18,
    "shield": 15,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Taurus",
    "popularity": 15,
    "attack": 10,
    "defense": 14,
    "dig": 15,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Ice Observer",
    "popularity": 21,
    "delay": 22,
    "attack": 14,
    "delay_item": 24,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Jean",
    "popularity": 10,
    "life": 15,
    "dig": 5,
    "attack": 0,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Moonie",
    "popularity": 7,
    "delay": 7,
    "defense": 17,
    "life": 17,
    "delay_item": 17,
    "dig": 7,
    "shield": 17,
    "attack": 0
  },
  {
    "name": "Ice",
    "popularity": 15,
    "defense": 10,
    "life": 25,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Goku SSJ God",
    "popularity": 15,
    "delay": 15,
    "attack": 15,
    "dig": 15,
    "shield": 15,
    "defense": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "(SET) Cat Mario",
    "popularity": 9,
    "attack": 9,
    "life": 9,
    "dig": 9,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Edward",
    "popularity": 3,
    "delay": 3,
    "life": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Rocker",
    "attack": 5,
    "defense": 5,
    "life": 5,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Blanka",
    "popularity": 8,
    "attack": 20,
    "defense": 20,
    "dig": 10,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Jengibre",
    "popularity": 7,
    "life": 5,
    "dig": 5,
    "attack": 0,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "James",
    "popularity": 7,
    "attack": 7,
    "defense": 7,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Goku SSJ4",
    "popularity": 10,
    "delay": 12,
    "defense": 8,
    "life": 10,
    "dig": 10,
    "attack": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Chavo del 8",
    "popularity": 15,
    "attack": 21,
    "defense": 10,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Zombie",
    "popularity": 17,
    "attack": 15,
    "life": 10,
    "delay_item": 10,
    "dig": 10,
    "shield": 15,
    "defense": 0,
    "delay": 0
  },
  {
    "name": "Nyx Lion",
    "popularity": 4,
    "delay": 9,
    "delay_item": 9,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Mage",
    "popularity": 24,
    "delay": 20,
    "attack": 10,
    "defense": 2,
    "life": 4,
    "delay_item": 20,
    "dig": 0,
    "shield": 0
  },
  {
    "name": "(SET) Luffy ll",
    "popularity": 21,
    "delay": 21,
    "attack": 14,
    "delay_item": 21,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Wolf",
    "defense": 12,
    "life": 15,
    "dig": 10,
    "shield": 6,
    "attack": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Pirate Evil",
    "attack": 5,
    "delay_item": 13,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Clown Evil",
    "popularity": 10,
    "delay": 4,
    "attack": 10,
    "defense": 4,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Freddy",
    "popularity": 5,
    "attack": 4,
    "defense": 15,
    "life": 4,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Delerium",
    "popularity": 20,
    "life": 22,
    "delay_item": 22,
    "dig": 11,
    "shield": 22,
    "attack": 0,
    "defense": 0,
    "delay": 0
  },
  {
    "name": "(SET) Chapulin",
    "defense": 16,
    "delay_item": 15,
    "dig": 15,
    "attack": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Sonic",
    "popularity": 15,
    "attack": 15,
    "defense": 15,
    "life": 15,
    "delay_item": 15,
    "dig": 15,
    "shield": 15,
    "delay": 0
  },
  {
    "name": "Vegeta SSJ2",
    "popularity": 15,
    "attack": 10,
    "defense": 25,
    "dig": 15,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Goku SSJ2",
    "popularity": 15,
    "defense": 25,
    "life": 10,
    "dig": 15,
    "attack": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) MetaBee",
    "popularity": 7,
    "defense": 14,
    "life": 14,
    "shield": 14,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "(Set) Golden Warrior",
    "popularity": 25,
    "attack": 30,
    "defense": 20,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Nyx Marth",
    "delay": 7,
    "defense": 12,
    "life": 12,
    "attack": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Emo",
    "popularity": 15,
    "delay": 10,
    "defense": 10,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Iron Man",
    "delay": 5,
    "attack": 10,
    "defense": 10,
    "dig": 5,
    "life": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Thor",
    "popularity": 10,
    "delay": 10,
    "defense": 10,
    "life": 10,
    "delay_item": 10,
    "shield": 10,
    "attack": 0,
    "dig": 0
  },
  {
    "name": "Holk",
    "attack": 15,
    "defense": 10,
    "life": 15,
    "shield": 10,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "(SET) Vegeta",
    "defense": 20,
    "life": 10,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Captain America",
    "delay": 10,
    "attack": 15,
    "dig": 10,
    "defense": 0,
    "life": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "DragonPower",
    "popularity": 8,
    "dig": 12,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Afro 80",
    "popularity": 10,
    "delay": 5,
    "attack": 3,
    "dig": 6,
    "defense": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Demon Boy",
    "delay": 7,
    "defense": 18,
    "life": 9,
    "attack": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Cow Boy",
    "popularity": 6,
    "delay": 6,
    "shield": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "Space Adventurer",
    "popularity": 20,
    "delay": 17,
    "attack": 14,
    "dig": 14,
    "defense": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Team Force",
    "attack": 3,
    "defense": 3,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Toilet Body",
    "popularity": 4,
    "delay": 9,
    "delay_item": 9,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Mutant",
    "popularity": 11,
    "delay": 9,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Roman Executioner",
    "popularity": 7,
    "delay": 7,
    "life": 7,
    "shield": 7,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay_item": 0
  },
  {
    "name": "Gaucho Body",
    "life": 6,
    "delay_item": 6,
    "shield": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0
  },
  {
    "name": "Celtic Warrior",
    "popularity": 6,
    "defense": 18,
    "dig": 9,
    "attack": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "African Boy",
    "popularity": 15,
    "delay": 10,
    "attack": 10,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Army Private Body",
    "popularity": 14,
    "attack": 14,
    "defense": 7,
    "dig": 17,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Cannon",
    "popularity": 12,
    "attack": 6,
    "defense": 6,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Nyx Abyss",
    "defense": 12,
    "life": 12,
    "shield": 12,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Hiphop Flamer",
    "popularity": 20,
    "delay": 17,
    "attack": 14,
    "dig": 14,
    "defense": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Thor's Wealth",
    "delay": 10,
    "attack": 10,
    "defense": 10,
    "life": 10,
    "dig": 10,
    "shield": 10,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Eros",
    "delay": 15,
    "defense": 15,
    "dig": 15,
    "attack": 0,
    "life": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Bone Man",
    "popularity": 9,
    "life": 10,
    "shield": 4,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Deamonic Body",
    "delay": 12,
    "defense": 18,
    "life": 18,
    "shield": 18,
    "attack": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Turtle Body",
    "attack": 9,
    "life": 9,
    "dig": 9,
    "defense": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "DJ Rapper",
    "popularity": 17,
    "defense": 17,
    "life": 17,
    "shield": 17,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Yoshiken",
    "popularity": 20,
    "defense": 14,
    "life": 14,
    "shield": 14,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Angel",
    "defense": 23,
    "life": 10,
    "shield": 10,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "(SET) Black Warrior",
    "attack": 15,
    "defense": 15,
    "dig": 15,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) PSY",
    "popularity": 15,
    "defense": 15,
    "life": 20,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Hero",
    "popularity": 10,
    "delay": 10,
    "defense": 15,
    "dig": 15,
    "attack": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Saint Seya",
    "popularity": 25,
    "attack": 20,
    "defense": 25,
    "shield": 15,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Racer",
    "popularity": 20,
    "defense": 15,
    "life": 10,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Luan Santana",
    "popularity": 25,
    "attack": 8,
    "life": 5,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Bob Marley",
    "popularity": 25,
    "defense": 15,
    "life": 5,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Bart Simpson",
    "popularity": 25,
    "delay": 13,
    "delay_item": 13,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "(SET) Inazuma Eleven",
    "popularity": 11,
    "delay": 11,
    "defense": 11,
    "delay_item": 11,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Anderson Silva",
    "delay": 8,
    "attack": 8,
    "defense": 8,
    "life": 8,
    "dig": 8,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Romeo",
    "popularity": 22,
    "attack": 5,
    "life": 23,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) YuGiOh",
    "popularity": 10,
    "attack": 10,
    "defense": 15,
    "life": 15,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Tsuna",
    "popularity": 20,
    "attack": 10,
    "delay_item": 20,
    "dig": 10,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "(SET) Shaman King",
    "delay": 10,
    "attack": 14,
    "defense": 10,
    "life": 14,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Sasuke Uchica",
    "popularity": 10,
    "attack": 15,
    "defense": 20,
    "life": 20,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Bleach",
    "popularity": 15,
    "attack": 16,
    "defense": 16,
    "life": 12,
    "dig": 17,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Natzu",
    "attack": 12,
    "defense": 12,
    "life": 12,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Paul",
    "defense": 15,
    "delay_item": 15,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "(SET) Death Note 2",
    "popularity": 20,
    "defense": 9,
    "life": 29,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Death Note",
    "popularity": 10,
    "delay": 10,
    "attack": 20,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Mummy",
    "popularity": 10,
    "defense": 10,
    "life": 23,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Kratoz",
    "popularity": 10,
    "attack": 15,
    "defense": 19,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Naruto",
    "popularity": 10,
    "attack": 11,
    "defense": 17,
    "life": 17,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Desert CVT",
    "delay": 10,
    "defense": 40,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Goku",
    "popularity": 10,
    "defense": 30,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Snow Devil Body",
    "delay": 12,
    "attack": 20,
    "delay_item": 8,
    "dig": 8,
    "defense": 0,
    "life": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "(SET) Luffy's Body",
    "popularity": 17,
    "delay": 17,
    "delay_item": 17,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Shamanist",
    "delay": 12,
    "life": 5,
    "delay_item": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Persian king",
    "popularity": 15,
    "life": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Musketeer",
    "popularity": 4,
    "life": 9,
    "shield": 9,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Latin Clothing",
    "popularity": 10,
    "delay": 6,
    "defense": 6,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Statue of Liberty",
    "popularity": 5,
    "attack": 20,
    "defense": 3,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Dracula",
    "popularity": 12,
    "delay_item": 9,
    "dig": 2,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Skeleton",
    "popularity": 25,
    "attack": 30,
    "defense": 20,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Kendo Uniform",
    "delay": 4,
    "attack": 7,
    "defense": 11,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Rocker Suit",
    "popularity": 8,
    "dig": 12,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Ice Hockey Uniform",
    "popularity": 2,
    "delay": 9,
    "defense": 12,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Elf Clothing",
    "popularity": 3,
    "delay": 6,
    "shield": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "Tuxedo",
    "popularity": 15,
    "defense": 3,
    "life": 6,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Space Marine",
    "attack": 3,
    "defense": 3,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "AntiCovid (SET)",
    "popularity": 10,
    "life": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Sweet Set",
    "popularity": 10,
    "defense": 10,
    "dig": 10,
    "attack": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  }
]
