var flags = [
  {
    "name": "Stone Spear",
    "popularity": 10,
    "defense": 6,
    "life": 10,
    "shield": 8,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Foxy",
    "popularity": 20,
    "delay": 5,
    "attack": 24,
    "defense": 9,
    "life": 9,
    "delay_item": 10,
    "dig": 10,
    "shield": 0
  },
  {
    "name": "Brown Guitar",
    "popularity": 20,
    "defense": 35,
    "life": 14,
    "delay_item": 14,
    "dig": 14,
    "attack": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Cyan Guitar",
    "popularity": 20,
    "attack": 10,
    "defense": 35,
    "dig": 10,
    "shield": 25,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Treasure Box",
    "popularity": 40,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Handcuffs",
    "defense": 10,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Power Sword",
    "popularity": 20,
    "attack": 35,
    "delay_item": 20,
    "dig": 25,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Shuriken",
    "attack": 12,
    "delay_item": 12,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Fire Snake",
    "popularity": 20,
    "delay": 15,
    "attack": 10,
    "life": 10,
    "dig": 20,
    "defense": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Traffic Lights",
    "popularity": 8,
    "attack": 8,
    "dig": 8,
    "shield": 8,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Galactic Gum",
    "popularity": 10,
    "shield": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Element Magic",
    "popularity": 10,
    "life": 30,
    "dig": 5,
    "attack": 0,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Element Nature",
    "popularity": 10,
    "life": 5,
    "dig": 30,
    "attack": 0,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Dragon Fossil",
    "popularity": 7,
    "attack": 10,
    "defense": 5,
    "life": 5,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Green Goblin",
    "popularity": 10,
    "defense": 5,
    "life": 5,
    "shield": 12,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Evil Eyes",
    "popularity": 5,
    "attack": 10,
    "defense": 5,
    "life": 5,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Fire Golem",
    "popularity": 10,
    "attack": 30,
    "defense": 5,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Ice Golem",
    "popularity": 10,
    "attack": 5,
    "defense": 30,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Pikachu Costume",
    "popularity": 15,
    "attack": 10,
    "dig": 10,
    "shield": 10,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "DragonBound Cake",
    "popularity": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Bright Light",
    "popularity": 15,
    "defense": 7,
    "life": 10,
    "shield": 10,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Hell Weapon",
    "popularity": 6,
    "attack": 6,
    "dig": 5,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Star Weapon",
    "popularity": 6,
    "defense": 6,
    "life": 5,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Magic Potion",
    "life": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Arrow Love",
    "popularity": 15,
    "attack": 15,
    "dig": 10,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "New Year's Firework",
    "popularity": 5,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Cookie box",
    "popularity": 10,
    "defense": 5,
    "life": 10,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Red Spear",
    "popularity": 10,
    "attack": 18,
    "life": 8,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Blue Spear",
    "popularity": 14,
    "attack": 14,
    "defense": 7,
    "life": 10,
    "dig": 7,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Pumpkin Tree",
    "popularity": 7,
    "delay": 10,
    "defense": 5,
    "life": 5,
    "attack": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Fire Squash",
    "attack": 10,
    "dig": 14,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Devil Pitchfork",
    "attack": 24,
    "dig": 12,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Cone",
    "popularity": 6,
    "attack": 12,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Observador Girl",
    "popularity": 14,
    "delay": 16,
    "delay_item": 16,
    "shield": 16,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0
  },
  {
    "name": "Neo Observador",
    "popularity": 20,
    "delay": 18,
    "defense": 20,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "KoreaGunba",
    "popularity": 18,
    "delay": 20,
    "life": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Bolivia",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Chile",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Popcorn SET",
    "popularity": 10,
    "delay": 12,
    "attack": 15,
    "dig": 12,
    "defense": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Trolly Bag Black",
    "popularity": 8,
    "defense": 16,
    "life": 8,
    "delay_item": 16,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Trolly Bag Red",
    "popularity": 8,
    "defense": 16,
    "life": 8,
    "delay_item": 16,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Panda F",
    "popularity": 8,
    "defense": 8,
    "life": 8,
    "dig": 8,
    "attack": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Panda M",
    "popularity": 8,
    "defense": 8,
    "life": 8,
    "dig": 8,
    "attack": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Love Letters",
    "popularity": 10,
    "delay": 10,
    "defense": 10,
    "delay_item": 15,
    "dig": 10,
    "shield": 15,
    "attack": 0,
    "life": 0
  },
  {
    "name": "Heart of Flowers",
    "popularity": 10,
    "delay": 5,
    "life": 8,
    "shield": 5,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay_item": 0
  },
  {
    "name": "Pink Sword",
    "attack": 20,
    "dig": 10,
    "shield": 15,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Candy Gift",
    "popularity": 5,
    "delay": 10,
    "attack": 2,
    "life": 2,
    "dig": 10,
    "defense": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Beating Heart",
    "popularity": 12,
    "life": 15,
    "shield": 20,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Strawberries",
    "popularity": 8,
    "defense": 8,
    "life": 8,
    "delay_item": 8,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Mecca Ball Sensor",
    "defense": 6,
    "life": 6,
    "delay_item": 6,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Acrobot",
    "popularity": 9,
    "life": 3,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Battle Axe",
    "delay": 3,
    "attack": 9,
    "life": 3,
    "defense": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Emerald Stick",
    "delay": 6,
    "attack": 6,
    "defense": 9,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Bower",
    "delay": 5,
    "defense": 10,
    "life": 10,
    "attack": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Antenna",
    "delay": 10,
    "delay_item": 8,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Cross",
    "delay": 10,
    "delay_item": 8,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Ghost lll",
    "popularity": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Death Sword",
    "popularity": 12,
    "attack": 17,
    "life": 12,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "2 Clouds",
    "popularity": 7,
    "delay": 7,
    "life": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Chiljido",
    "defense": 25,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Mace",
    "attack": 25,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Norway Key",
    "popularity": 5,
    "shield": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Penguin Stick",
    "life": 10,
    "shield": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Jungle Chief",
    "popularity": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Poseidon Jewel",
    "popularity": 15,
    "defense": 35,
    "life": 10,
    "delay_item": 10,
    "dig": 10,
    "shield": 10,
    "attack": 0,
    "delay": 0
  },
  {
    "name": "Chief Symbol",
    "popularity": 6,
    "delay": 9,
    "defense": 3,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "XMAS Gifts",
    "popularity": 6,
    "shield": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Sonokong",
    "popularity": 10,
    "delay_item": 30,
    "shield": 30,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0
  },
  {
    "name": "Chinese Mask",
    "popularity": 5,
    "attack": 25,
    "delay_item": 5,
    "dig": 20,
    "shield": 5,
    "defense": 0,
    "life": 0,
    "delay": 0
  },
  {
    "name": "Knight Symbol",
    "delay": 15,
    "attack": 5,
    "life": 10,
    "dig": 15,
    "defense": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Heavenly",
    "popularity": 10,
    "delay": 5,
    "attack": 20,
    "defense": 7,
    "life": 7,
    "delay_item": 7,
    "dig": 7,
    "shield": 21
  },
  {
    "name": "BooDoo B",
    "delay": 6,
    "attack": 6,
    "delay_item": 3,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "BooDoo A",
    "delay": 6,
    "defense": 6,
    "life": 3,
    "attack": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "JiRoDo",
    "delay": 3,
    "attack": 6,
    "shield": 6,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Magic Broom",
    "delay": 3,
    "delay_item": 9,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "ChungRyongDo",
    "popularity": 3,
    "attack": 9,
    "dig": 3,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Stick Candy",
    "popularity": 6,
    "life": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Palm Tree (Small)",
    "popularity": 3,
    "defense": 6,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Palm Tree (Big)",
    "popularity": 6,
    "defense": 6,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Cross Spear",
    "popularity": 3,
    "attack": 9,
    "delay_item": 3,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Feather Fan",
    "delay_item": 6,
    "dig": 3,
    "shield": 3,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0
  },
  {
    "name": "Lond Dream",
    "popularity": 6,
    "attack": 6,
    "life": 6,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Russia",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Japan",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Mexico",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Marvin T.M",
    "popularity": 15,
    "attack": 40,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Warrior Of Light",
    "popularity": 20,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Ecuador",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Italy",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "England",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Argentina",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Portugal",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "USA",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Korea",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Costa Rica",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "China",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Brazil",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "South Africa",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Paraguay",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Slovenia",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Spain",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Denmark",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Uruguay",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Senegal",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "France",
    "popularity": 6,
    "delay_item": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "White Flag",
    "popularity": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Yellow Flag",
    "popularity": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Black Flag",
    "popularity": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Violet Flag",
    "popularity": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Red Flag",
    "popularity": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Blue Flag",
    "popularity": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Soul Light",
    "popularity": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Soul Rose",
    "popularity": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Cosmo",
    "popularity": 5,
    "delay": 5,
    "shield": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "Condorito",
    "popularity": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Madara Uchiha",
    "popularity": 15,
    "delay": 10,
    "life": 5,
    "dig": 10,
    "attack": 0,
    "defense": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Birthday Cake",
    "popularity": 10,
    "delay": 5,
    "attack": 5,
    "dig": 5,
    "defense": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Wedding Cake",
    "popularity": 10,
    "attack": 5,
    "life": 5,
    "dig": 5,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Ray Flag",
    "attack": 10,
    "defense": 5,
    "life": 5,
    "shield": 5,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Nak Flag",
    "delay": 5,
    "attack": 5,
    "defense": 5,
    "shield": 5,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Mage Flag",
    "delay": 5,
    "defense": 5,
    "life": 5,
    "shield": 5,
    "attack": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Lightning Flag",
    "delay": 5,
    "attack": 5,
    "life": 5,
    "dig": 5,
    "defense": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Grub Flag",
    "popularity": 5,
    "defense": 5,
    "life": 5,
    "shield": 5,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Electrico Flag",
    "popularity": 5,
    "attack": 5,
    "life": 5,
    "shield": 5,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Knight Flag",
    "delay": 5,
    "attack": 5,
    "life": 5,
    "dig": 5,
    "defense": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Dragon Flag",
    "attack": 5,
    "defense": 5,
    "life": 5,
    "delay_item": 5,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Boomer Flag",
    "popularity": 5,
    "defense": 5,
    "delay_item": 5,
    "dig": 5,
    "attack": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "BigFoot Flag",
    "popularity": 5,
    "delay": 5,
    "attack": 5,
    "life": 5,
    "defense": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Armor Flag",
    "delay": 5,
    "attack": 5,
    "life": 5,
    "dig": 5,
    "defense": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Aduka Flag",
    "attack": 5,
    "life": 5,
    "delay_item": 5,
    "dig": 5,
    "defense": 0,
    "delay": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "A.Sate Flag",
    "popularity": 5,
    "delay": 5,
    "dig": 5,
    "shield": 5,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "J.D Flag",
    "attack": 5,
    "defense": 5,
    "life": 5,
    "delay_item": 5,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Turtle Flag",
    "popularity": 5,
    "delay": 5,
    "defense": 5,
    "dig": 5,
    "attack": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Trico Flag",
    "delay": 5,
    "attack": 5,
    "life": 5,
    "shield": 5,
    "defense": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Ice Flag II",
    "popularity": 5,
    "attack": 5,
    "life": 5,
    "shield": 5,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Globo Mars",
    "popularity": 10,
    "defense": 5,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Crash",
    "delay": 5,
    "defense": 10,
    "delay_item": 5,
    "shield": 5,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "popularity": 0
  },
  {
    "name": "Sword Art Online",
    "popularity": 10,
    "delay": 5,
    "attack": 9,
    "life": 10,
    "defense": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Anonymous",
    "popularity": 12,
    "delay_item": 12,
    "shield": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0
  },
  {
    "name": "Thunder",
    "delay": 7,
    "defense": 10,
    "life": 20,
    "shield": 15,
    "attack": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Zeno Sama",
    "popularity": 20,
    "defense": 20,
    "delay_item": 20,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Euryalus",
    "popularity": 10,
    "delay_item": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Enchanted",
    "popularity": 5,
    "attack": 5,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Bomberman",
    "popularity": 10,
    "attack": 5,
    "dig": 9,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Red Flash",
    "delay": 12,
    "defense": 10,
    "life": 5,
    "shield": 10,
    "attack": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Blue Fire",
    "popularity": 5,
    "life": 5,
    "delay_item": 5,
    "shield": 5,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0
  },
  {
    "name": "Fireworks ll",
    "popularity": 10,
    "delay": 5,
    "life": 5,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Burned Doll Man",
    "attack": 10,
    "defense": 5,
    "life": 5,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Pyrotechnic",
    "popularity": 10,
    "life": 10,
    "shield": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Serpentine boot",
    "popularity": 10,
    "delay": 5,
    "delay_item": 5,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Pyrotechnic ll",
    "popularity": 5,
    "attack": 5,
    "life": 5,
    "shield": 5,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Champagne",
    "popularity": 5,
    "defense": 10,
    "shield": 15,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Pokedex",
    "popularity": 12,
    "attack": 9,
    "defense": 5,
    "dig": 5,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Aurora (Male)",
    "delay": 15,
    "life": 10,
    "shield": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Saeds",
    "popularity": 10,
    "delay": 10,
    "delay_item": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Peru Flag",
    "popularity": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Soul Tree",
    "popularity": 25,
    "life": 35,
    "shield": 35,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Spaceship",
    "popularity": 12,
    "delay": 10,
    "life": 10,
    "delay_item": 4,
    "shield": 4,
    "attack": 0,
    "defense": 0,
    "dig": 0
  },
  {
    "name": "Michael",
    "popularity": 15,
    "delay": 10,
    "defense": 5,
    "shield": 5,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "Shenlong II",
    "popularity": 15,
    "attack": 20,
    "defense": 10,
    "life": 10,
    "dig": 7,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "MegaZord",
    "popularity": 12,
    "delay": 5,
    "defense": 15,
    "shield": 10,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "Head with snakes",
    "popularity": 7,
    "attack": 12,
    "defense": 12,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Sword Fire",
    "attack": 25,
    "defense": 5,
    "life": 10,
    "dig": 8,
    "shield": 5,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Moster Flame",
    "popularity": 5,
    "delay": 6,
    "attack": 6,
    "delay_item": 6,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Inca",
    "popularity": 20,
    "attack": 20,
    "life": 20,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Ent",
    "popularity": 5,
    "attack": 7,
    "delay_item": 7,
    "dig": 3,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Zeus II",
    "popularity": 7,
    "delay": 7,
    "attack": 15,
    "defense": 3,
    "dig": 10,
    "shield": 7,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "Demon Shadow",
    "popularity": 10,
    "attack": 20,
    "delay_item": 10,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Elucidator",
    "popularity": 10,
    "attack": 30,
    "life": 3,
    "delay_item": 3,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Taurus",
    "attack": 22,
    "shield": 10,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Bat",
    "popularity": 10,
    "attack": 12,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Tiger Toy",
    "popularity": 10,
    "defense": 10,
    "life": 10,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Lion Toy",
    "popularity": 25,
    "delay": 12,
    "delay_item": 5,
    "dig": 15,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Fish Toy",
    "popularity": 5,
    "delay": 10,
    "attack": 5,
    "shield": 10,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "Fan",
    "popularity": 10,
    "delay": 15,
    "delay_item": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Chucky Knife",
    "popularity": 10,
    "attack": 15,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Napoleon Cape",
    "popularity": 5,
    "delay": 10,
    "attack": 5,
    "dig": 10,
    "defense": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Yoshi",
    "popularity": 20,
    "delay": 10,
    "defense": 10,
    "delay_item": 10,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Donkey Kong",
    "popularity": 20,
    "attack": 20,
    "defense": 10,
    "dig": 10,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Fox 2 Heads",
    "popularity": 10,
    "attack": 15,
    "life": 15,
    "dig": 7,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Harp",
    "popularity": 15,
    "life": 5,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Arc",
    "popularity": 15,
    "attack": 9,
    "dig": 5,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Zeus",
    "popularity": 10,
    "delay": 5,
    "attack": 5,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Golden Zeus",
    "popularity": 15,
    "attack": 10,
    "life": 10,
    "shield": 5,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Rose",
    "popularity": 22,
    "attack": 3,
    "defense": 2,
    "life": 11,
    "delay_item": 11,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "By Star",
    "popularity": 20,
    "delay_item": 10,
    "dig": 20,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Roses Big",
    "popularity": 25,
    "dig": 10,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Fairy Observer",
    "popularity": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Broomstick",
    "popularity": 20,
    "delay": 5,
    "dig": 5,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Sun DB",
    "popularity": 25,
    "delay_item": 10,
    "dig": 10,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Observer Flag",
    "popularity": 25,
    "delay": 15,
    "shield": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "Hero Flag",
    "popularity": 10,
    "delay": 15,
    "attack": 10,
    "delay_item": 15,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Angel Female",
    "popularity": 10,
    "delay": 10,
    "attack": 5,
    "defense": 5,
    "dig": 5,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Angel Male",
    "popularity": 10,
    "delay": 10,
    "attack": 5,
    "defense": 5,
    "dig": 5,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Pichu",
    "popularity": 20,
    "dig": 10,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Black Fox",
    "popularity": 10,
    "delay": 5,
    "attack": 2,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Ice Flag",
    "popularity": 25,
    "delay": 5,
    "shield": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "Fire Gold",
    "attack": 12,
    "defense": 12,
    "life": 9,
    "dig": 10,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Picture",
    "popularity": 10,
    "delay": 2,
    "attack": 5,
    "delay_item": 5,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Gold Dragon",
    "popularity": 25,
    "delay": 9,
    "attack": 5,
    "delay_item": 6,
    "shield": 5,
    "defense": 0,
    "dig": 0,
    "life": 0
  },
  {
    "name": "Observer Girl",
    "popularity": 20,
    "delay": 9,
    "attack": 5,
    "delay_item": 6,
    "dig": 10,
    "defense": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Snowfall",
    "popularity": 30,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Clowndog",
    "popularity": 15,
    "attack": 5,
    "shield": 10,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Parca",
    "popularity": 15,
    "delay": 11,
    "life": 2,
    "delay_item": 9,
    "dig": 11,
    "attack": 0,
    "defense": 0,
    "shield": 0
  },
  {
    "name": "Octopus",
    "popularity": 10,
    "delay": 17,
    "attack": 5,
    "delay_item": 18,
    "dig": 2,
    "defense": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Element Water",
    "popularity": 20,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Element Shadow",
    "popularity": 20,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Element Ice",
    "popularity": 20,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Element Fire",
    "popularity": 20,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Cat Mario",
    "popularity": 9,
    "attack": 9,
    "life": 9,
    "dig": 9,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Rocker",
    "attack": 5,
    "defense": 5,
    "life": 5,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Blanka",
    "attack": 10,
    "defense": 10,
    "life": 20,
    "dig": 10,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "boom!",
    "dig": 17,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "g-emo",
    "defense": 17,
    "dig": 3,
    "attack": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Aqua Dragon",
    "delay": 5,
    "attack": 15,
    "defense": 15,
    "dig": 10,
    "life": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Chavo del 8",
    "popularity": 10,
    "life": 15,
    "delay_item": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "(SET) Chilidrina",
    "popularity": 15,
    "attack": 5,
    "life": 5,
    "shield": 5,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Horse Fire",
    "attack": 16,
    "life": 17,
    "delay_item": 5,
    "shield": 12,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0
  },
  {
    "name": "(SET) Luffy ll",
    "popularity": 19,
    "delay": 19,
    "delay_item": 19,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Monster",
    "popularity": 15,
    "delay": 5,
    "attack": 10,
    "delay_item": 20,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Military",
    "popularity": 5,
    "delay": 2,
    "attack": 25,
    "defense": 10,
    "dig": 12,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Wolf",
    "delay": 5,
    "attack": 10,
    "defense": 3,
    "life": 3,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Aemeth",
    "popularity": 20,
    "delay": 5,
    "defense": 23,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Viuda Negra",
    "popularity": 10,
    "attack": 14,
    "defense": 14,
    "dig": 10,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Chapulin",
    "delay": 15,
    "delay_item": 15,
    "dig": 8,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Kit SSJ2",
    "delay": 15,
    "delay_item": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "(SET) MetaBee",
    "popularity": 10,
    "delay": 12,
    "defense": 12,
    "shield": 25,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "Flag Tournament",
    "defense": 10,
    "life": 12,
    "shield": 5,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "(SET) Thor",
    "popularity": 15,
    "attack": 25,
    "dig": 15,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Lillymon",
    "popularity": 16,
    "delay": 8,
    "life": 12,
    "delay_item": 8,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "shield": 0
  },
  {
    "name": "(SET) Vegeta",
    "attack": 5,
    "life": 12,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Teddy Flag",
    "popularity": 6,
    "attack": 9,
    "life": 5,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Moon Red",
    "attack": 12,
    "dig": 12,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Chocobo",
    "popularity": 15,
    "defense": 4,
    "delay_item": 20,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Cow Flag",
    "popularity": 10,
    "defense": 5,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Butterfly",
    "popularity": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Inner Strength",
    "delay": 7,
    "delay_item": 14,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Horse Shadow",
    "attack": 15,
    "life": 15,
    "shield": 10,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Dragon Thunder",
    "popularity": 15,
    "attack": 12,
    "dig": 7,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Dragon Glass",
    "attack": 15,
    "life": 15,
    "shield": 10,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Ola Ke Ase",
    "popularity": 35,
    "attack": 3,
    "life": 3,
    "shield": 5,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "(SET) Black Warrior",
    "popularity": 14,
    "attack": 14,
    "life": 14,
    "dig": 10,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) PSY",
    "popularity": 30,
    "delay": 10,
    "delay_item": 5,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Hero",
    "popularity": 13,
    "delay": 13,
    "delay_item": 13,
    "dig": 10,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "(SET) Inazuma Eleven",
    "delay": 11,
    "life": 11,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) YuGiOh",
    "popularity": 25,
    "life": 5,
    "delay_item": 5,
    "dig": 8,
    "attack": 0,
    "defense": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "(SET) Shaman King",
    "popularity": 15,
    "attack": 15,
    "defense": 15,
    "delay_item": 10,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "(SET) Shaman King F",
    "popularity": 15,
    "attack": 15,
    "life": 15,
    "delay_item": 10,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "(SET) Sasuke Uchica",
    "attack": 15,
    "life": 22,
    "shield": 15,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "(SET) Bleach",
    "popularity": 10,
    "attack": 15,
    "life": 15,
    "delay_item": 15,
    "shield": 15,
    "defense": 0,
    "dig": 0,
    "delay": 0
  },
  {
    "name": "(SET) Natzu",
    "popularity": 15,
    "attack": 15,
    "life": 6,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Paul",
    "attack": 12,
    "defense": 6,
    "life": 6,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Witch",
    "delay": 8,
    "defense": 8,
    "life": 8,
    "attack": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Mummy",
    "attack": 10,
    "dig": 10,
    "shield": 10,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "(SET) Sakura Card Captor",
    "popularity": 10,
    "delay": 10,
    "defense": 10,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Dark Magic",
    "attack": 15,
    "defense": 6,
    "life": 6,
    "shield": 10,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "(SET) Rylai",
    "popularity": 10,
    "defense": 15,
    "delay_item": 15,
    "shield": 30,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0
  },
  {
    "name": "(SET) Kratoz",
    "popularity": 10,
    "delay": 5,
    "attack": 10,
    "delay_item": 20,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "(SET) Sakura",
    "popularity": 10,
    "delay": 8,
    "attack": 15,
    "delay_item": 15,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "(SET) Naruto",
    "popularity": 10,
    "defense": 10,
    "life": 15,
    "delay_item": 15,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Kitten Cloud",
    "delay": 8,
    "life": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Desert CVT",
    "life": 35,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Goku",
    "popularity": 25,
    "attack": 17,
    "defense": 17,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Sailor moon",
    "popularity": 10,
    "delay": 5,
    "attack": 10,
    "defense": 5,
    "shield": 10,
    "dig": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "Shenlong",
    "attack": 28,
    "delay_item": 10,
    "shield": 10,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0
  },
  {
    "name": "Gift",
    "popularity": 10,
    "life": 7,
    "delay_item": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Pala",
    "attack": 8,
    "dig": 14,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Rocker Boy",
    "popularity": 10,
    "attack": 10,
    "defense": 10,
    "delay_item": 10,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Zombie Pirate",
    "popularity": 12,
    "delay": 12,
    "dig": 12,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Luffy's Flag",
    "popularity": 17,
    "delay": 17,
    "delay_item": 17,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Wedding Balloon",
    "delay": 6,
    "life": 9,
    "delay_item": 9,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Wedding Flower",
    "popularity": 6,
    "delay": 6,
    "life": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Anonymous",
    "popularity": 12,
    "delay_item": 12,
    "shield": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0
  },
  {
    "name": "Zeno Sama",
    "popularity": 20,
    "defense": 20,
    "delay_item": 20,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Aurora (Female)",
    "delay": 15,
    "life": 10,
    "shield": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0
  }
]