var glasses = [
  {
    "name": "Harry Potter",
    "popularity": 10,
    "defense": 12,
    "shield": 12,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Mario Gold",
    "popularity": 12,
    "life": 12,
    "delay_item": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Popeye",
    "popularity": 10,
    "attack": 15,
    "life": 9,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Dark Phoenix",
    "popularity": 20,
    "delay": 20,
    "delay_item": 25,
    "dig": 20,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Fire Phoenix",
    "popularity": 20,
    "attack": 22,
    "defense": 24,
    "life": 23,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Spark",
    "attack": 7,
    "defense": 10,
    "dig": 5,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Pikachu Costume",
    "popularity": 10,
    "delay": 10,
    "dig": 5,
    "shield": 10,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "Bright Light",
    "delay": 10,
    "attack": 5,
    "dig": 5,
    "defense": 0,
    "life": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Glotzy",
    "popularity": 15,
    "delay": 10,
    "attack": 8,
    "shield": 12,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0
  },
  {
    "name": "Galactic Sword",
    "popularity": 6,
    "life": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Cone II",
    "popularity": 8,
    "attack": 8,
    "defense": 8,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Popcorn SET",
    "popularity": 10,
    "delay": 12,
    "attack": 12,
    "life": 15,
    "dig": 12,
    "defense": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Chinese Light",
    "popularity": 8,
    "life": 8,
    "delay_item": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Ring",
    "popularity": 12,
    "defense": 15,
    "delay_item": 15,
    "shield": 20,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0
  },
  {
    "name": "Big Heart",
    "popularity": 12,
    "life": 15,
    "shield": 20,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Teddy Bear",
    "popularity": 10,
    "defense": 10,
    "delay_item": 16,
    "shield": 12,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0
  },
  {
    "name": "Bow and Arrow",
    "attack": 12,
    "delay_item": 8,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Love Potion",
    "popularity": 7,
    "life": 10,
    "shield": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Ring of Hearts",
    "popularity": 10,
    "life": 12,
    "shield": 8,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Cupid Card",
    "popularity": 8,
    "delay": 7,
    "life": 8,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Fishing Rod",
    "popularity": 5,
    "delay": 15,
    "attack": 5,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Mage Mask",
    "attack": 5,
    "defense": 20,
    "shield": 5,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Raon",
    "popularity": 2,
    "delay": 10,
    "attack": 2,
    "life": 2,
    "dig": 10,
    "defense": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "American Football",
    "popularity": 8,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Rubber Ducky",
    "popularity": 10,
    "delay_item": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Gigantic Shades",
    "popularity": 10,
    "shield": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Roses",
    "popularity": 15,
    "life": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Thunder Dragon",
    "attack": 21,
    "defense": 24,
    "life": 22,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Sinulog Cross",
    "delay": 10,
    "life": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Festival Spear",
    "delay": 5,
    "attack": 15,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Ember Dragon",
    "popularity": 12,
    "delay": 18,
    "attack": 20,
    "dig": 24,
    "defense": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Torch",
    "delay": 4,
    "delay_item": 14,
    "dig": 7,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Magician's Hat",
    "popularity": 20,
    "life": 10,
    "dig": 18,
    "attack": 0,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Uma Sword",
    "popularity": 8,
    "attack": 12,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Batarang",
    "popularity": 12,
    "attack": 3,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Bikini Goggles",
    "popularity": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Basketball",
    "popularity": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Heavenly",
    "popularity": 19,
    "delay": 21,
    "delay_item": 18,
    "dig": 10,
    "shield": 20,
    "attack": 0,
    "defense": 0,
    "life": 0
  },
  {
    "name": "Ultra Instinct",
    "popularity": 11,
    "attack": 18,
    "defense": 18,
    "life": 18,
    "dig": 11,
    "shield": 11,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Rune Blade",
    "delay": 4,
    "attack": 16,
    "life": 12,
    "defense": 0,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Barong Sword",
    "attack": 6,
    "defense": 3,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Kris",
    "attack": 9,
    "defense": 6,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Sibat at Kalasag",
    "attack": 6,
    "defense": 6,
    "shield": 6,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Badminton Set",
    "popularity": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Mr. Sushi",
    "popularity": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Curious",
    "popularity": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Angry",
    "popularity": 12,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Bald Eagle",
    "attack": 8,
    "defense": 8,
    "life": 3,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Dizzy Glasses",
    "popularity": 2,
    "delay": 7,
    "dig": 8,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Mask",
    "popularity": 2,
    "defense": 5,
    "delay_item": 7,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Pig Mask",
    "popularity": 9,
    "life": 9,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Monkey Mask",
    "popularity": 9,
    "life": 6,
    "shield": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Red Glasses",
    "delay": 6,
    "delay_item": 3,
    "shield": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "popularity": 0
  },
  {
    "name": "Rimless specs",
    "popularity": 3,
    "life": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Ski Goggle",
    "popularity": 3,
    "defense": 6,
    "delay_item": 6,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "One-eyed",
    "popularity": 3,
    "delay_item": 3,
    "shield": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0
  },
  {
    "name": "Elvis Shades",
    "popularity": 9,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Hockey Mask",
    "defense": 6,
    "life": 6,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Black Painting",
    "popularity": 3,
    "defense": 3,
    "life": 3,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Red Nose",
    "popularity": 9,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Laser Goggle",
    "attack": 9,
    "defense": 3,
    "life": 3,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Gunshot",
    "delay": 3,
    "life": 6,
    "dig": 3,
    "attack": 0,
    "defense": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Swimming Goggles",
    "delay_item": 6,
    "dig": 3,
    "shield": 3,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0
  },
  {
    "name": "Battle Goggle S",
    "popularity": 3,
    "life": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Battle Goggle G",
    "popularity": 3,
    "attack": 6,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Battle Goggle B",
    "popularity": 3,
    "life": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Urban",
    "popularity": 15,
    "delay": 10,
    "delay_item": 10,
    "dig": 10,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Night Vision",
    "attack": 3,
    "defense": 3,
    "dig": 6,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Zoro Mask",
    "popularity": 6,
    "defense": 3,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Black Glasses",
    "popularity": 3,
    "shield": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "YinYang Painting",
    "popularity": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Cross Scar",
    "popularity": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Pilot Goggle",
    "popularity": 3,
    "dig": 3,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Battle Goggle",
    "popularity": 6,
    "dig": 3,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Sanji",
    "popularity": 15,
    "attack": 15,
    "defense": 5,
    "dig": 10,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Timmy Turner",
    "popularity": 10,
    "attack": 5,
    "delay_item": 9,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Maga Oscura",
    "popularity": 15,
    "defense": 5,
    "delay_item": 10,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Louise de La Valliere",
    "delay": 10,
    "defense": 10,
    "dig": 9,
    "attack": 0,
    "life": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Shadow",
    "attack": 15,
    "life": 10,
    "dig": 10,
    "defense": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Wiss",
    "popularity": 10,
    "attack": 10,
    "dig": 10,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Madara Uchiha",
    "popularity": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Scepter",
    "popularity": 15,
    "defense": 25,
    "shield": 25,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Petals",
    "popularity": 15,
    "life": 25,
    "dig": 15,
    "attack": 0,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Crash",
    "popularity": 10,
    "attack": 10,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Sword Art Online",
    "delay": 10,
    "defense": 10,
    "dig": 9,
    "attack": 0,
    "life": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Anonymous",
    "popularity": 10,
    "defense": 25,
    "delay_item": 10,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Shadow Warrior",
    "popularity": 20,
    "delay": 15,
    "delay_item": 20,
    "shield": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0
  },
  {
    "name": "Zeno Sama",
    "popularity": 12,
    "attack": 25,
    "delay_item": 5,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Euryalus",
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Atenea",
    "popularity": 10,
    "defense": 6,
    "delay_item": 5,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Sparks of lights",
    "popularity": 10,
    "delay": 15,
    "life": 10,
    "delay_item": 10,
    "shield": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0
  },
  {
    "name": "Flare",
    "popularity": 5,
    "delay": 5,
    "attack": 5,
    "defense": 5,
    "life": 5,
    "delay_item": 5,
    "dig": 5,
    "shield": 5
  },
  {
    "name": "Cyber Dragon",
    "popularity": 20,
    "delay": 6,
    "attack": 24,
    "delay_item": 25,
    "dig": 22,
    "defense": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Soul Sword",
    "popularity": 6,
    "attack": 7,
    "shield": 6,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Thunder Sword",
    "popularity": 15,
    "delay": 10,
    "life": 12,
    "delay_item": 10,
    "dig": 20,
    "attack": 0,
    "defense": 0,
    "shield": 0
  },
  {
    "name": "King Kong",
    "popularity": 10,
    "defense": 20,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Fire Skull",
    "popularity": 7,
    "life": 10,
    "dig": 3,
    "shield": 4,
    "attack": 0,
    "defense": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Spear",
    "popularity": 6,
    "attack": 5,
    "delay_item": 5,
    "dig": 13,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Sun",
    "popularity": 10,
    "defense": 20,
    "dig": 10,
    "shield": 5,
    "attack": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Inca Legend",
    "popularity": 10,
    "delay": 21,
    "delay_item": 21,
    "dig": 6,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Shield Player",
    "popularity": 10,
    "defense": 20,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "My Dog F",
    "popularity": 15,
    "attack": 9,
    "defense": 9,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "My Dog M",
    "popularity": 15,
    "attack": 9,
    "defense": 9,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Flower",
    "popularity": 11,
    "life": 11,
    "delay_item": 11,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Anivia",
    "popularity": 20,
    "delay": 20,
    "dig": 15,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Pikapi",
    "popularity": 10,
    "life": 10,
    "shield": 5,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Portal",
    "popularity": 25,
    "delay": 10,
    "dig": 15,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Thor",
    "popularity": 10,
    "delay": 5,
    "attack": 20,
    "defense": 5,
    "life": 5,
    "delay_item": 5,
    "dig": 10,
    "shield": 5
  },
  {
    "name": "Libra",
    "popularity": 5,
    "delay": 5,
    "attack": 5,
    "defense": 5,
    "life": 5,
    "delay_item": 5,
    "dig": 5,
    "shield": 5
  },
  {
    "name": "Evil Dog",
    "popularity": 10,
    "delay": 5,
    "attack": 20,
    "delay_item": 10,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "White Phoenix",
    "popularity": 10,
    "delay": 20,
    "delay_item": 25,
    "dig": 15,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Red Phoenix",
    "attack": 10,
    "defense": 25,
    "life": 24,
    "delay_item": 3,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Nice Wolf F",
    "popularity": 5,
    "life": 5,
    "dig": 5,
    "attack": 0,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Nice Wolf M",
    "popularity": 5,
    "life": 5,
    "dig": 5,
    "attack": 0,
    "defense": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Goku SSJ God",
    "popularity": 15,
    "delay": 10,
    "attack": 10,
    "defense": 10,
    "life": 10,
    "dig": 15,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Rocker",
    "attack": 5,
    "defense": 5,
    "life": 5,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Kit SSJ4",
    "popularity": 10,
    "delay": 8,
    "attack": 12,
    "defense": 12,
    "dig": 8,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Chilidrina",
    "popularity": 15,
    "delay": 5,
    "attack": 10,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Bat",
    "popularity": 10,
    "delay": 3,
    "attack": 3,
    "defense": 3,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "I ♥ YOU",
    "popularity": 15,
    "attack": 3,
    "life": 15,
    "shield": 5,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Ball of Fire",
    "popularity": 10,
    "delay": 10,
    "attack": 5,
    "defense": 5,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Sr Cat",
    "popularity": 12,
    "attack": 10,
    "dig": 5,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Chapulin",
    "life": 15,
    "shield": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Kit SSJ2",
    "popularity": 15,
    "attack": 15,
    "defense": 15,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) MetaBee",
    "delay": 15,
    "attack": 12,
    "life": 8,
    "delay_item": 8,
    "defense": 0,
    "dig": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Black Dragon",
    "attack": 10,
    "defense": 24,
    "life": 24,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Gold Dragon",
    "delay": 12,
    "attack": 12,
    "defense": 12,
    "life": 12,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Green Dragon",
    "popularity": 10,
    "delay": 10,
    "life": 10,
    "delay_item": 10,
    "dig": 20,
    "attack": 0,
    "defense": 0,
    "shield": 0
  },
  {
    "name": "Red Dragon",
    "attack": 9,
    "defense": 15,
    "life": 15,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Dragon",
    "popularity": 10,
    "delay": 13,
    "attack": 24,
    "dig": 20,
    "defense": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Iron Man",
    "popularity": 10,
    "attack": 15,
    "dig": 10,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Thor",
    "popularity": 10,
    "delay": 6,
    "life": 10,
    "delay_item": 10,
    "dig": 10,
    "attack": 0,
    "defense": 0,
    "shield": 0
  },
  {
    "name": "(SET) Lillymon",
    "popularity": 12,
    "attack": 12,
    "life": 12,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Vegeta",
    "delay": 5,
    "attack": 10,
    "defense": 10,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Captain America",
    "delay": 12,
    "attack": 12,
    "defense": 12,
    "dig": 15,
    "shield": 15,
    "life": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Fire Dragon",
    "delay": 12,
    "attack": 12,
    "defense": 12,
    "life": 12,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Mega Power",
    "attack": 10,
    "defense": 24,
    "life": 24,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Sun Cute",
    "popularity": 11,
    "life": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Nebula",
    "popularity": 12,
    "attack": 13,
    "life": 13,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Sword Laser",
    "delay": 2,
    "attack": 12,
    "defense": 10,
    "dig": 0,
    "life": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Guitar",
    "life": 20,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Stressed Z",
    "popularity": 15,
    "life": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Sword Warrior",
    "popularity": 10,
    "delay": 10,
    "life": 10,
    "delay_item": 10,
    "dig": 20,
    "attack": 0,
    "defense": 0,
    "shield": 0
  },
  {
    "name": "Dragon Sword",
    "attack": 18,
    "defense": 18,
    "life": 18,
    "delay_item": 11,
    "shield": 11,
    "dig": 0,
    "delay": 0,
    "popularity": 0
  },
  {
    "name": "(SET) Black Warrior",
    "popularity": 10,
    "delay": 5,
    "defense": 12,
    "dig": 12,
    "attack": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) PSY",
    "attack": 10,
    "delay_item": 6,
    "dig": 6,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "shield": 0
  },
  {
    "name": "Hero",
    "popularity": 15,
    "attack": 20,
    "delay_item": 10,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "(SET) YuGiOh",
    "popularity": 15,
    "attack": 15,
    "defense": 15,
    "shield": 20,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "(SET) Shaman King",
    "popularity": 15,
    "attack": 15,
    "defense": 10,
    "delay_item": 10,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "(SET) Shaman King F",
    "popularity": 15,
    "attack": 15,
    "life": 10,
    "delay_item": 10,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "(SET) Sasuke Uchica",
    "popularity": 5,
    "delay": 15,
    "defense": 15,
    "dig": 15,
    "attack": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Bleach",
    "popularity": 10,
    "delay": 20,
    "delay_item": 20,
    "dig": 5,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "(SET) Natzu",
    "popularity": 10,
    "life": 15,
    "shield": 15,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "(SET) Paul",
    "popularity": 10,
    "attack": 18,
    "defense": 8,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Sakura Card Captor",
    "popularity": 6,
    "attack": 15,
    "defense": 6,
    "life": 6,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Dark Magic",
    "defense": 15,
    "life": 8,
    "shield": 8,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "(SET) Rylai",
    "popularity": 10,
    "delay": 10,
    "defense": 5,
    "delay_item": 25,
    "shield": 10,
    "attack": 0,
    "dig": 0,
    "life": 0
  },
  {
    "name": "(SET) Kratoz",
    "popularity": 10,
    "delay": 6,
    "attack": 15,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Sakura",
    "popularity": 8,
    "delay": 6,
    "attack": 5,
    "defense": 8,
    "life": 15,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Naruto",
    "popularity": 15,
    "delay": 8,
    "attack": 12,
    "life": 8,
    "defense": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Desert CVT",
    "attack": 35,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Goku",
    "delay": 10,
    "dig": 10,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "(SET) Sailor moon",
    "popularity": 10,
    "delay": 5,
    "attack": 15,
    "life": 5,
    "defense": 0,
    "dig": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "D-Balls",
    "popularity": 15,
    "defense": 10,
    "shield": 15,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "(SET) Luffy's Scar",
    "popularity": 17,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Nunchakus",
    "popularity": 8,
    "attack": 12,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Napoleon",
    "popularity": 15,
    "life": 10,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Red Light Saber",
    "attack": 15,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Blue Light Saber",
    "defense": 8,
    "shield": 7,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Rem",
    "popularity": 6,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Snorkel",
    "popularity": 4,
    "defense": 6,
    "life": 6,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Rimless specs",
    "popularity": 3,
    "life": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Ski Goggle",
    "popularity": 3,
    "defense": 6,
    "delay_item": 6,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "One-Eyed",
    "popularity": 3,
    "delay_item": 3,
    "shield": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0
  },
  {
    "name": "Elvis Shades",
    "popularity": 9,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Black Painting",
    "popularity": 3,
    "defense": 3,
    "life": 3,
    "attack": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Red Makeup",
    "popularity": 6,
    "life": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Black Glasses",
    "popularity": 3,
    "shield": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0
  },
  {
    "name": "Urban",
    "popularity": 15,
    "delay": 10,
    "delay_item": 10,
    "dig": 10,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "shield": 0
  },
  {
    "name": "Battle Goggle P",
    "popularity": 3,
    "attack": 6,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Battle Goggle O",
    "popularity": 3,
    "defense": 6,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Night Vision",
    "attack": 3,
    "defense": 3,
    "dig": 6,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Zoro Mask",
    "popularity": 6,
    "defense": 3,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "YinYang Painting",
    "popularity": 3,
    "attack": 0,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Pilot Goggle",
    "popularity": 3,
    "dig": 3,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Battle Goggle",
    "popularity": 6,
    "dig": 3,
    "attack": 0,
    "defense": 0,
    "life": 0,
    "delay": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Zeno Sama",
    "popularity": 12,
    "attack": 25,
    "delay_item": 5,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "shield": 0
  },
  {
    "name": "Fuchsia Dragon",
    "delay": 12,
    "attack": 12,
    "defense": 12,
    "life": 12,
    "dig": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  },
  {
    "name": "Blue Light Saber",
    "defense": 8,
    "shield": 7,
    "attack": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0
  },
  {
    "name": "Red Light Saber",
    "attack": 15,
    "defense": 0,
    "dig": 0,
    "life": 0,
    "delay": 0,
    "popularity": 0,
    "delay_item": 0,
    "shield": 0
  }
]